TNV-19: extend the fw_version command to show the FPGA revision
EmcraftSystems/tinyclunx33_zephyr_example pull request #2
Opened 2024-02-16 19:41 UTC by ayurtsev

2024-02-17 07:41 UTC, vladimirkhusainov-emcraft requested changes

2024-02-17 07:41 UTC, vladimirkhusainov-emcraft commented on src/main.c
> +#define CSR_OFFSET	0xB2000000
Shouldn't those register offsets and definitions go into some header file? It is not unthinkable they would be needed in more files than just main.c.

Another comment is that it is probably a good idea to dedicate a source file to implement a new shell command (or, possibly, several shell commands can go into a related source file). I envision us implementing many shell commands; doesn't look as a good strategy to put them all into main.c.

2024-02-18 22:13 UTC, ayurtsev commented on src/main.c
> +#define CSR_OFFSET	0xB2000000
I've addressed the above comments, please take a look at the updated code.

2024-02-19 06:25 UTC, vladimirkhusainov-emcraft approved these changes

2024-02-19 09:22 UTC, merged