TNV-11: increase RAM size available to Zephyr to 512K
EmcraftSystems/tinyclunx33_zephyr_example pull request #3
Opened 2024-02-16 22:15 UTC by ayurtsev

2024-02-17 13:37 UTC, dnbazhenov requested changes

2024-02-17 13:37 UTC, dnbazhenov commented on litex.overlay
> +	reg = <0x40000000 0x80000>;
If I'm correct there are only 5 LRAM blocks in the FPGA. Please, check and fix if needed.

2024-02-18 21:40 UTC, ayurtsev commented on litex.overlay
> +	reg = <0x40000000 0x80000>;
Yes, there are 5 LRAM blocks, and only one is allocated to the RISC-V core. The above patch extends amount of RAM available to Zephyr to the whole LRAM block that is accessible by the CPU. I don't see what other changes may be needed here.

2024-02-19 19:54 UTC, closed without merging

2024-02-19 19:55 UTC, ayurtsev commented
Closed as obsolete. The memory settings will be revised.